<?php

namespace PokedexBundle\Repository;
use Doctrine\ORM\EntityRepository;
use PokedexBundle\Entity\Attaque;
use Doctrine\ORM\QueryBuilder;

/**
 * AttaqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttaqueRepository extends \Doctrine\ORM\EntityRepository
{
}
