<?php

namespace PokedexBundle\Repository;

/**
 * AttaqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttaqueRepository extends \Doctrine\ORM\EntityRepository
{
}
