<?php

namespace PokedexBundle\Repository;



use Doctrine\ORM\EntityRepository;
use PokedexBundle\Entity\Pokemon;
use Doctrine\ORM\QueryBuilder;
/**
 * PokemonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PokemonRepository extends EntityRepository
{


}
